# Wandb settings
project: 'AstroM3'
use_wandb: True

# Dataset settings
dataset: 'MeriDK/AstroM3Dataset'
classes: ['EW', 'SR', 'EA', 'RRAB', 'EB', 'ROT', 'RRC', 'HADS', 'M', 'DSCT']
num_classes: 10
seq_len: 200
mode: 'meta'
data_sub: 'full'

# Metadata model parameters
m_input_dim: 34
m_hidden_dim: 512
m_dropout: 0.19168856047566107

# Training settings
use_pretrain: null
epochs: 50
batch_size: 512
lr: 0.002744981242271558
beta1: 0.9219791256930212
beta2: 0.999
weight_decay: 0.00026179047214550745
early_stopping_patience: 6
clip_grad: False
save_weights: True
weights_path: './weights/'

# Scheduler settings
scheduler: 'ReduceLROnPlateau'
scheduler_factor: 0.3720521973024151
scheduler_patience: 3
warmup_epochs: 10