# Wandb settings
project: 'AstroM3'
use_wandb: True

# Dataset settings
dataset: 'MeriDK/AstroM3Dataset'
classes: ['EW', 'SR', 'EA', 'RRAB', 'EB', 'ROT', 'RRC', 'HADS', 'M', 'DSCT']
num_classes: 10
seq_len: 200
mode: 'meta'
data_sub: 'sub10'

# Metadata model parameters
m_input_dim: 34
m_hidden_dim: 512
m_dropout: 0.1479383968245285

# Training settings
use_pretrain: null
epochs: 50
batch_size: 512
lr: 0.009586101387197628
beta1: 0.960355167407052
beta2: 0.999
weight_decay: 0.0016692845865161668
early_stopping_patience: 6
clip_grad: False
save_weights: True
weights_path: './weights/'

# Scheduler settings
scheduler: 'ReduceLROnPlateau'
scheduler_factor: 0.48040637245293494
scheduler_patience: 3
warmup_epochs: 10