# Wandb settings
project: 'AstroM3'
use_wandb: True

# Dataset settings
dataset: 'MeriDK/AstroM3Dataset'
classes: ['EW', 'SR', 'EA', 'RRAB', 'EB', 'ROT', 'RRC', 'HADS', 'M', 'DSCT']
num_classes: 10
seq_len: 200
mode: 'spectra'
data_sub: 'sub10'

# Spectra model parameters
s_dropout: 0.219251883044236
s_conv_channels: [3, 64, 64, 32, 32]
s_kernel_size: 3
s_mp_kernel_size: 4

# Training settings
use_pretrain: null
epochs: 50
batch_size: 512
lr: 0.005733557394025984
beta1: 0.9706049382983424
beta2: 0.999
weight_decay: 0.008311501808684634
early_stopping_patience: 6
clip_grad: True
clip_value: 5
save_weights: True
weights_path: './weights/'

# Scheduler settings
scheduler: 'ReduceLROnPlateau'
scheduler_factor: 0.914364478102646
scheduler_patience: 3
warmup_epochs: 10